### ISSUE TITLE
Token invalidation problem

### ISSUE THREAD

**Issue by jdlrobson** [jdlrobson/someday#40]
When trying to sign in...
```
JSON Web Token Validation Problem, iat1545791978/1545791966
    at /home/jdlrobson/app/someday/node_modules/passport-mediawiki-oauth/lib/passport-mediawiki-oauth/oauth.js:148:23
    at passBackControl (/home/jdlrobson/app/someday/node_modules/passport-mediawiki-oauth/lib/passport-mediawiki-oauth/oauth-patches.js:114:15)
    at IncomingMessage.<anonymous> (/home/jdlrobson/app/someday/node_modules/passport-mediawiki-oauth/lib/passport-mediawiki-oauth/oauth-patches.js:134:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jdlrobson** [comment]
Pushed change 147473d42887b925667ce34e5aafca8e173c4cd5
